### PR TITLE
Fix function name

### PR DESCRIPTION
**Pull request by swsnr**
It's `servant/stop` :)

### CODE REVIEW

**Comment by rejeep** [comment]
Ahh nice. Need to add some tests :)

I gave you commit access, push away!

**Comment by swsnr** [comment]
I am currently trying servant to power unit tests for my little pkg-info library.  If that goes well, I'll use it to threw an EPL testsuite together.

**Comment by swsnr** [comment]
Ok, I see, it's not yet compatible with snapshot.  I'll try to get #3 solved, in order to make it usable.

By the way, you don't accidentally call package.el functions in the package.el server for the Cask testsuite?  It just occurred to me that this might be a possible reason for the test failures on Emacs snapshot.

**Comment by rejeep** [comment]
Nice package, didn't know about it. What functions will you expose in the API? I'm asking because of this code in Servant https://github.com/rejeep/servant.el/blob/master/servant.el#L143-L198. I was looking after some package for that, but didn't find any. Maybe pkg-info is the one?

So then pkg-info would require servant and servant pkg-info... :)

**Comment by rejeep** [comment]
> By the way, you don't accidentally call package.el functions in the package.el server for the Cask testsuite? It just occurred to me that this might be a possible reason for the test failures on Emacs snapshot.

No, the server is always started with stable Emacs on Travis (see https://github.com/cask/cask/blob/master/.travis.yml#L23)

**Comment by swsnr** [comment]
`pkg-info` is not really intended to programmatically work with version numbers.  It is more a piece of common code found in packages to show their own version number to the user.

For instance, Flycheck uses it to provide `M-x flycheck-version` which shows the package version (from MELPA) and the real version (from the header) to the user.  It's mostly intended for debugging, to find out what Flycheck version the user has installed, and where it probably came from.

Instead of duplicating the version number in a `defconst`, I thought it more clever to just extract it from the header.  Originally the whole code was part of Flycheck, until @bbatsov asked me to move it into a package so that he could use it in his packages as well.

**Comment by swsnr** [comment]
I see.  We need further research then.

**Pull request merged**
