### PR TITLE
V0.1 wip

### PR DESCRIPTION
**Pull request by rejeep**
@lunaryorn Do you use Servant for any of your projects? If you do, I think it would be good if you tried this branch out before I merge it because Servant is not very well tested.

I don't think there's any other projects using this?

### CODE REVIEW

**Comment by swsnr** [comment]
@rejeep I can test this branch with my pkg-info test suite, but it'll take time. I'm a bit loaded with work currently.

**Comment by rejeep** [comment]
No worries. These changes are for Cask and I can just link it for now. Do it when you find the time!

**Comment by swsnr** [comment]
@rejeep If they work for Cask, why don't just go ahead and merge them?  After all, Servant isn't an important library, but just a testing tool.

**Comment by rejeep** [comment]
Haven't tried it for Cask yet, but you are right. It's not the end of the world if it breaks. Thanks!

**Pull request merged**
